import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Playfair_Display, Space_Grotesk } from "next/font/google";

const playinit = Playfair_Display({
  subsets: ["latin"],
  variable: "--play-fair-display",
});
const spaceGrotesk_init = Space_Grotesk({
  subsets: ["latin"],
  variable: "--space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={" " + playinit.variable + " " + spaceGrotesk_init.variable}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
